quarkus:
  application:
    name: quarkus-s3-demo

  s3:
    aws:
      region: us-east-1
      credentials:
        type: static
        static-provider:
          access-key-id: *****************
          secret-access-key: *************
